#Don't change this value unless you want to reset the config
ConfigVersion: 4
#If true the plugin will automatically download the latest version of AFK+ when a newer version is released
UpdateDownload: false
#Should action or warnings be used on players with the admin permission?
AdminAction: false
#Time in seconds until someone will be set as AFK
TimeUntilAFK: 60
#This is how long after a player starts AFK that they will receive the warning message WarnMessage in messages.yml
#Set this number higher than the TimeUntilAction value to disable
#This timer starts when the player becomes AFK!
TimeUntilWarn: 210
#Time in seconds that a player has to be AFK for before they are kicked.
#NOTE: This timer only starts when a player becomes AFK
TimeUntilAction: 240
#Can players who are AFK be hurt?
AFKDamage: false
#This is a list of the enabled listeners for AFK
EnabledListeners:
  BlockPlace: true
  BlockBreak: true
  BlockInteract: true
  Attack: true
  Move: true
  Chat: true
  Command: true
  Join: true
#Actions can be COMMAND, MESSAGE, KICK
Action: COMMAND
#The command to be run for COMMAND and the message for KICK or MESSAGE
#NOTE: add a ':' between commands if you want to run more than one
#EG, ActionVariable: "warn %NAME being AFK for too long:kill %NAME"
#This will warn the player(if you have a warn plugin) and then kill them
ActionVariable: "kick %NAME AFK for more than 5 Minutes"