# Don't change this value unless you want to reset the config
ConfigVersion: 5
# If true the plugin will automatically download the latest version of AFK+ when a newer version is released
UpdateDownload: false
# Should action or warnings be used on players with the admin permission?
AdminAction: false
# Can players who are AFK be hurt?
AFKDamage: false
# This is a list of the enabled listeners for AFK
EnabledListeners:
  BlockPlace: true
  BlockBreak: true
  BlockInteract: true
  Attack: true
  Move: true
  Chat: true
  Command: true
  Join: true
# Actions can be COMMAND, MESSAGE, KICK
Action: COMMAND
# The command to be run for COMMAND and the message for KICK or MESSAGE
# NOTE: add a ':' between commands if you want to run more than one
# EG, ActionVariable: "warn %NAME being AFK for too long:kill %NAME"
# This will warn the player(if you have a warn plugin) and then kill them
ActionVariable: "kick %NAME% AFK for more than 5 Minutes"
# AFK Start and stop commands are run when a player goes into or exits AFK respectively. The player will get a tick of no detections
# before and after these commands are run, this means you can teleport the player if they are AFK and it wont count as the player moving
# Be aware that these commands are run by console and that the plugin doesn't store the players location
# Set this to an empty string for no command
AFKStart: "tell %PLAYER% You have been set as AFK as you have been inactive"
AFKStop: "tell %PLAYER% Welcome back!"

# Custom Permissions section
Permissions:
  afkplus,player:
    # Which players should be given this permission automatically
    # 0=no one 1=all players 2=OPs
    Default: 1
    # If a player has more than 1 permission then they will be given the permssion with the highest Priority value
    Priority: 1
    # Will they be able to check if other players are AFK or reload the plugin, users with this permission will also receive update messages
    Admin: 0
    # Can they use the /afk command
    UseCommand: 1
    # Time in seconds until someone will be set as AFK
    TimeToAFK: 60
    # This is how long after a player starts AFK that they will receive the warning message WarnMessage in messages.yml
    # Set this number higher than the TimeUntilAction value to disable
    # This timer starts when the player becomes AFK!
    TimeToWarn: 210
    # Time in seconds that a player has to be AFK for before they are kicked.
    # NOTE: This timer only starts when a player becomes AFK
    TimeToAction: 240
  afkplus,admin:
    Default: 2
    Priority: 2
    Admin: 1
    TimeToAFK: 120
    TimeToWarn: 270
    TimeToAction: 300